### ISSUE TITLE
no caso de uso em que se coloca um node na tree e se remove e volta a colocar um novo da segfault

### ISSUE THREAD

**Issue by migas342** [diogo0501/SD_22_23#15]
possivelmente tem a ver com o tree em si

**Comment by diogo0501** [comment]
Isto acontece quando eleminamos a raiz da arvore. Mesmo utilizando o tree.o disponibilizado pelos stores, da seg fault no lado do tree, o que pode significar que esse caso de uso nao foi tido em conta

**Comment by diogo0501** [comment]
Professor atualizou o tree.o e este erro já nao se verifica
